### ISSUE TITLE
Strict DFS traversal

### ISSUE THREAD

**Issue by guanzo** [ipfs/js-ipfs-unixfs#359]
The [Trustless Gateway](https://specs.ipfs.tech/http-gateways/trustless-gateway/) spec is being productionized by Saturn, Daghaus and possibly others. It's important for DAG traversal clients to be able to consume CARs with blocks in DFS order as this is optimal for streaming and incremental verification. While DFS isn't required by the spec, it seems to be the preferred traversal order as it's the only [explicitly mentioned order](https://specs.ipfs.tech/http-gateways/trustless-gateway/#car-order-content-type-parameter), the other being "unknown".

This is the section that performs BFS, there may be more though.

https://github.com/ipfs/js-ipfs-unixfs/blob/8a271b2e4e268f18b7e6a3e5569df8cce21897b5/packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.ts#L53-L127

**Comment by rvagg** [comment]
I believe that section is doing DFS. See the bottom most part of it. Just collecting links but then serially walking those links and resolving what's below them.

https://github.com/web3-storage/freeway I believe is making use of this same code to produce DFS order for us. I think originally they had some BFS code internally that they had to unwind but from what I understand the unixfs internals aren't the problem area.

**Comment by guanzo** [comment]
OK I really hope I'm not misunderstanding something.

> Just collecting links

The issue is, `blockstore.get` is called for each link, before resolving each links children.

https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.ts#L78

**Comment by rvagg** [comment]
mmm, you're probably right about that! not sure about the async iteration going on there but probably doing all those blockstore fetches in parallel _first_; maybe worth finding out how freeway is using this code to do it? or perhaps it's just using js-unixfs for this side of it instead

**Comment by rvagg** [comment]
Or ... perhaps we haven't noticed traversal order problems with freeway because large file fetching is more rare, maybe I need to go back and look at the error logs. You have to have a pretty big file to end up with multiple layers.

**Comment by guanzo** [comment]
Yep I've been using this lib for months without issue. It was only until I tried rendering a 50MB image that I noticed this problem.

**Comment by achingbrain** [comment]
The traversal is DFS, that is, the leaf node data is emitted depth-first, but internally the exporter applies an optimisation to load all the children in the DAG as soon as they are encountered.

The links are processed in-order and as soon as they are ready rather than waiting for the last to load before the first is processed.

This speeds up the case for when the blockstore has to go to the network or it uses some other slow retrieval method, as it has a headstart for when you do actually need a sibling block, but is why it's called in an order that looks like it's doing BFS.

A quick fix might be to expose a config option for the `it-parallel` `concurrency` parameter and pass it in [here](https://github.com/ipfs/js-ipfs-unixfs/blob/8a271b2e4e268f18b7e6a3e5569df8cce21897b5/packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.ts#L86-L88) - if you set it to `1` then the blocks should be loaded from the blockstore in an order consistent with DFS.

**Comment by alanshaw** [comment]
@rvagg freeway does not use the unixfs exporter to create CARs with DFS block ordering.

**Comment by guanzo** [comment]
Ok that makes sense. 

For context, Saturn retrieval clients expect CAR blocks to be in DFS order, and it's implemented by having the traversal client (in this case js-ipfs-unixfs) ask the blockstore for blocks in the expected order. There isn't really an easy workaround in userland since the blockstore lacks any traversal context, so a workaround would be appreciated 🙏 .
